[package]
name = "tabs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.9.0", features = ["smol"] }
iced_aw = { version = "0.5.2", features = ["tabs", "icons"] }
